### ISSUE TITLE
Inconsistency between Kernel Results and Torch Results

### ISSUE THREAD

**Issue by sleepcoo** [Raincleared-Song/sparse_gpu_operator#2]
I compiled and ran the project, and called compare_tensors(cuda_res, torch_res, tolerance) with the tolerance set to 1e-5. I found that basically none of the index results align. Is this expected? Also, I would like to ask if this kernel does not support batch*hidden as input?
<img width="906" alt="image" src="https://github.com/Raincleared-Song/sparse_gpu_operator/assets/118525388/935f4749-10d0-4fe3-a274-c7cb670ddb14">
#### Res
```
index,num_nonzero_elements,%,cuda_time,torch_time
0,1053,9.566,47.53589630126953,94.46287155151367
Index 13: diff = 0.0078125
Index 24: diff = -2.0
Index 69: diff = -0.5
Index 279: diff = 0.125
Omit......... 
```

**Comment by Raincleared-Song** [comment]
I'm sorry for this issue. This is actually attributed to the low absolute precision of `bfloat16` at relatively large scales. When we test the scripts, we find that the output results of these scripts (i.e.,`cuda_res` and `torch_res`) are generally larger than 200, at which scale the precision becomes lower and an absolute error up to $2$ is possible.

We fix this issue in this [commit](https://github.com/Raincleared-Song/sparse_gpu_operator/commit/4d8a41fb5bff1dee506475a648c06855e4dc91f7), which modifies the implementation of `compare_tensors` to apply tolerance to relative error. Results demonstrate that the relative errors of our operators are no larger than 1%.

**Comment by sleepcoo** [comment]
> I'm sorry for this issue. This is actually attributed to the low absolute precision of `bfloat16` at relatively large scales. When we test the scripts, we find that the output results of these scripts (i.e.,`cuda_res` and `torch_res`) are generally larger than 200, at which scale the precision becomes lower and an absolute error up to 2 is possible.
> 
> We fix this issue in this [commit](https://github.com/Raincleared-Song/sparse_gpu_operator/commit/4d8a41fb5bff1dee506475a648c06855e4dc91f7), which modifies the implementation of `compare_tensors` to apply tolerance to relative error. Results demonstrate that the relative errors of our operators are no larger than 1%.

Have you considered supporting batch processing?
@Raincleared-Song

**Comment by Raincleared-Song** [comment]
> Have you considered supporting batch processing?

I've just contacted our engineer. The batch processing feature can be ready this week.

**Comment by sleepcoo** [comment]
> > Have you considered supporting batch processing?
> 
> I've just contacted our engineer. The batch processing feature can be ready this week.

When supporting batch processing, are the selected columns for different tokens placed into a one-dimensional vec_sparse `[hidden_size]`, or into vec_sparse `[batch, hidden_size]`? I am inclined to believe it is `[hidden_size]`, as that is the approach taken in DejaVu.

**Comment by Sxy-17** [comment]
> When supporting batch processing, are the selected columns for different tokens placed into a one-dimensional vec_sparse `[hidden_size]`, or into vec_sparse `[batch, hidden_size]`? I am inclined to believe it is `[hidden_size]`

Take ffn_23 as an example, to reuse weight data, the naive implementation will consider loading the matrix column “selected by” vec_sparse once and performing matrix-vector multiplication with vectors of multiple batches.  

The operator with batch processing is still under active development in [this](https://github.com/Sxy-17/sparse_gpu_operator/tree/ffn_23_multi_batch) repo. After the naive implementation is completed, it will be pushed to the current repo as a new branch.

**Comment by Raincleared-Song** [comment]
If there do not exist other problems, may I close the issue? @sleepcoo
