### ISSUE TITLE
operator_23 slower than torch counterpart at low sparsity

### ISSUE THREAD

**Issue by Jimskns** [Raincleared-Song/sparse_gpu_operator#3]
@Raincleared-Song 
Hi, I ran run_test_23.py on A100 GPU， and found that torch_launch_ffn_fuse_23 is slower that vanilla torch one at low sparsity(lower than 30%).
![issue](https://github.com/Raincleared-Song/sparse_gpu_operator/assets/147290174/62e84631-129e-4e1f-a8bb-31a8c0c80bce)

Is that resonable? What's the possible causes? 
Thanks!

**Comment by Raincleared-Song** [comment]
This is a normal situation. Compared with PyTorch APIs, our operators are tailored for sparse vector-matrix multiplication but are not good at dense operations. Concretely, we do not use some acceleration techniques of cuBLAS, which are adopted in PyTorch for dense tensor operations. Therefore, we may fall behind PyTorch in operations of relatively dense tensors.

**Comment by Jimskns** [comment]
@Raincleared-Song Got it, thank you~
