### ISSUE TITLE
Question about L1Norm when training

### ISSUE THREAD

**Issue by Jimskns** [Raincleared-Song/sparse_gpu_operator#4]
Hi @Raincleared-Song ,
Confusion about performing L1norm on which dim given the input x of shape [bs, seq_len, hidden]. 
Is the L1 Norm output in the shape of [bs,] or [bs, seq_len]? 
Thanks~

**Comment by Raincleared-Song** [comment]
I'm sorry but our operator on the master branch does not support batch operations at present. In other words, the batch size must be 1 to run properly.
However, the operator with batch processing is already under active development in [this](https://github.com/Sxy-17/sparse_gpu_operator/tree/ffn_23_multi_batch) repo. After the naive implementation is completed, it will be pushed to the current repo as a new branch.

**Comment by Jimskns** [comment]
Thanks for your reply. 
But actually I'm focusing on the output shape of L1 Norm in formula 2 during training stage:
![L1formula](https://github.com/Raincleared-Song/sparse_gpu_operator/assets/147290174/86023148-a7b2-4e2b-9c74-c661db3872a2)
The bs is unlikely to be 1 during training, is that right?

**Comment by Raincleared-Song** [comment]
You are right. As our operators are tailored for inference at the beginning, we did not add the batch processing feature. Also, we did not apply the operators in the training stage.
Still, you may pay attention to our developing feature in the following repo.

> However, the operator with batch processing is already under active development in [this](https://github.com/Sxy-17/sparse_gpu_operator/tree/ffn_23_multi_batch) repo. After the naive implementation is completed, it will be pushed to the current repo as a new branch.

**Comment by Jimskns** [comment]
OK，thanks~
